layout_spectrum: 0.5157234
typography_spectrum: 0.9052933
color:
  lightness: 0.639679
  brandStrength: 0.4418753
  saturation: 0.209439
  rhythmicContrast: 0.5512764
  brandColors:
    - '#B2A392'
    - '#30271F'
    - '#FFFDF0'
name: Practice Yoga
